version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-container

    environment:
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - ./mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    networks:
      - my-network

  spring-boot-app:
    image: spring-boot-app
    container_name: spring-boot-app-container
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
