server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/project_final
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    database: mysql
    show-sql: false


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

springdoc:
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  swagger-ui:
    path: /swagger-ui-custom.html
    enabled: true
    groups-order: ASC
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    doc-expansion: none
  cache:
    disabled: true
  model-and-view-allowed: true

kakao:
  client:
    id: 214a201e2f4c682aa352ec136a79189b
    secret: qlOIf0kweHr54gT7WF92fPnR4VgCX6bc
  redirect:
    url: http://125.132.216.190:5544/login/oauth2/code/kakao



