server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database: mysql
    show-sql: false
  batch:
    jdbc:
      initialize-schema: never
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB

  profiles:
    active: dev  # 기본 프로파일을 dev로 설정

logging:
  level:
    root: INFO
    org.springframework.batch: ERROR
    org.hibernate: WARN
  file:
    name: logs/spring-boot-app.log
    encoding: UTF-8

springdoc:
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  swagger-ui:
    path: /swagger-ui-custom.html
    enabled: true
    groups-order: ASC
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    doc-expansion: none

kakao:
  client:
    id: ${KAKAO_CLIENT_ID}
    secret: ${KAKAO_CLIENT_SECRET}
  redirect:
    url: ${KAKAO_REDIRECT_URL}

