spring:
  datasource:
    url: jdbc:mysql://localhost:3306/project_final
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

cloud:
  aws:
    s3:
      bucket: 1-1-final-project
    region:
      static: ${S3_REGION}
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}

server:
  port: 5544
